### PR TITLE
Fixed new HTML report generation issue.

### LINKED ISSUE #7: Improve TEAM Engine Compatibility
When running a local installation of TEAM Engine, ets-cdb10 test results on a CDB kept on the local filesystem will produce a test report that is not parsed by TEAM Engine. Because it is not parsed, you must manually view the test results to see which tests passed/failed.

I will check out other ETS repositories to see how this is done properly.

### PR DESCRIPTION
**Pull request by keshav-nangare**
1. Fixed new HTML report generation issue.
2. Added new field in CTL form to upload local file.

Fixed #7.

### CODE REVIEW

**Comment by ghobona** [comment]
@openfirmware To test the PR, including file upload.

**Comment by openfirmware** [comment]
I was able to get the new HTML output format working. I will test the file upload form next.

**Comment by openfirmware** [comment]
The HTML output is now working correctly. I was also able to test the ZIP file upload function through the TEAM Engine Web UI, and it works although there are new failures.

When running TestNG through Eclipse, it now fails because the TestNG properties ([`src/main/resources/org/opengis/cite/cdb10/testng.xml`](https://github.com/opengeospatial/ets-cdb10/blob/master/src/main/resources/org/opengis/cite/cdb10/testng.xml)) uses a *relative* path to refer to the internal CDB that is used for testing. As the ETS could be installed anywhere, I cannot hardcode an absolute path; instead the relative path must be converted to an absolute URL in the `SuiteFixtureListener`. I will try adding some code to check for relative URLs, and if it works I will rebase and merge this pull request.

**Comment by ghobona** [comment]
DIscussion on 2020-07-22

@openfirmware To fix Issue https://github.com/opengeospatial/ets-cdb10/issues/26 first and then do a rebase to merge this PR(or it changes) on top of the solution to Issue https://github.com/opengeospatial/ets-cdb10/issues/26.

**Comment by openfirmware** [comment]
I was able to test the PR with the latest changes to how IUT paths are handled. I added a commit with an "if statement" to only unzip a file if ".zip" is present, otherwise using a path to a local CDB would fail in TEAM Engine and in Eclipse.

**Pull request closed without merging**
