### PR TITLE
Add validation of GSModel archive files

### LINKED ISSUE #6: Validate GSModel zip archives
The following files can reside in ZIP archives:

1. GSModelGeometry
2. GSModelTexture
3. GSModelMaterial
4. GSModelDescriptor
5. GSModelInteriorGeometry
6. GSModelInteriorTexture
7. GSModelInteriorMaterial
8. GSModelInteriorDescriptor

ZIP archives should be inspected and validated.

### PR DESCRIPTION
**Pull request by openfirmware**
This commit adds CDB Structure Test classes to validate GSModel archives. Closes #6.

These classes are now validated:

1. GSModelGeometry
2. GSModelTexture
3. GSModelMaterial
4. GSModelDescriptor
5. GSModelInteriorGeometry
6. GSModelInteriorTexture
7. GSModelInteriorMaterial
8. GSModelInteriorDescriptor

Tested:

* ZIP archive filenames
* ZIP archive file size limit (32 MB)
* ZIP archive readability (Does the Java parser open it without errors?) 
* ZIP archive entry filenames
* ZIP archive entry compression

Tests affected:

* Test 40
* Test 69
* Test 70
* Test 71
* Test 72

Additional Fixes:

* References in test descriptions were using the wrong document revision number; this has now been fixed
* Validation logic has been re-used from Tile Structure tests

### CODE REVIEW

**Comment by openfirmware** [comment]
I adjusted the test methods to search for GSModel archives in the proper directory. Previously it had been searching in:

```
CDB > Tiles > 300_GSModelGeometry > *.zip
```

Now it will properly recurse the LOD and UREF directories to find the archives:

```
CDB > Tiles > 300_GSModelGeometry > L07 > U38 > *.zip
```

This should solve the issue with GSModel test methods being skipped instead of validated.

**Comment by openfirmware** [comment]
I also refactored the GSModel code to avoid nested "for" loops for scanning entries in the CDB, and instead it will use lambdas to evaluate each entry. It seems lambdas are a Java 8 feature, and will not work with Java 7. I can switch the code back to the previous style if we need to keep Java 7 support.

**Comment by ghobona** [comment]
We use Java 8 on the Beta and Production TEAM Engine instances. So you can keep the code in Java 8 style.

@openfirmware Please let Jeremie know when the GSModel tests are ready to be reviewed.

**Comment by openfirmware** [comment]
There is an issue in the PR with how the test suite is executed, and it is affecting all Java versions:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project ets-cdb10: Compilation failure: Compilation failure: 
1260[ERROR] /home/travis/build/GeoSensorWebLab/ets-cdb10/src/main/java/org/opengis/cite/cdb10/cdbStructure/GSModel/GSModelGeometryStructureTests.java:[66,61] lambda expressions are not supported in -source 1.7
```

Travis Logs: https://travis-ci.org/github/GeoSensorWebLab/ets-cdb10/builds/732415121

I think it is the same issue that Jeremie is experiencing when trying to run the test suite. I will track down where this issue is occuring.

**Comment by openfirmware** [comment]
I will manually merge in a commit to fix the conflicts with the main branch

**Comment by ghobona** [comment]
@openfirmware I see that you have fixed the Java version issue. Shall I merge this PR?

**Comment by openfirmware** [comment]
@ghobona yes, it should be good to merge now.

**Pull request merged**
